spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
          #唯一标识符,goods微服务
          - id: changgou_goods_route
            #用户请求需要路由到该服务[指定要路由的服务]
            #uri: http://localhost:18081
            #使用loadbalanceclient实现负载均衡，后面goods是微服务的名称
            uri: lb://goods
            #路由断言，路由规则配置
            predicates:
            #用户请求的域名规则配置，所有以cloud.itheima.com的请求都将被路由到http://localhost:18081
            #- Host=cloud.itheima.com**
            #所有以/api/../**开始的请求，都将被路由到http://localhost:18081/api/../**
            - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
            filters:
            #用户所有请求路径中都加一个/brand前缀，例如请求http://localhost:8001->真实请求http://localhost:8001/brand
            #- PrefixPath=/brand
            #会将请求路径中的第一个去掉
            - StripPrefix=1
            #局部限流过滤器
            - name: RequestRateLimiter #请求数限流 名字不能随便写，使用默认的factory
              args:
                key-resolver: "#{@ipKeyResolver}"
                #每秒钟只允许有一个请求
                redis-rate-limiter.replenishRate: 1
                #允许并发有四个请求[宽限的个数]
                redis-rate-limiter.burstCapacity: 4
          #唯一标识符,用户微服务
          - id: changgou_user_route
            uri: lb://user
            predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
            filters:
            - StripPrefix=1
          #唯一标识符,订单微服务
          - id: changgou_order_route
            uri: lb://order
            predicates:
              - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
            filters:
              - StripPrefix=1

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
